#------------------------------------------------------------------------------
# FILE:         action.yaml
# CONTRIBUTOR:  Jeff Lill
# COPYRIGHT:    Copyright (c) 2005-2021 by neonFORGE LLC.  All rights reserved.
#
# The contents of this repository are for private use by neonFORGE, LLC. and may not be
# divulged or used for any purpose by other organizations or individuals without a
# formal written and signed agreement with neonFORGE, LLC.

#------------------------------------------------------------------------------
# Fails the workflow when an inpout is true.

name: fail
description: "Fails the workflow when an input is true"
inputs:
  fail:
    description: "Indicates whether the workflow should fail"
    required: true
  message:
    description: "Optionally specifies the error message to be included in the log"
    required: false
    default: "*** Workflow Failed ***"
runs:
  using: node12
  main: action.js
